CREATE TABLE IF NOT EXISTS users (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    email VARCHAR(254) NOT NULL,
    password_hash VARCHAR(255) NOT NULL,
    full_name VARCHAR(120) NOT NULL,
    phone VARCHAR(10) NOT NULL,
    role VARCHAR(20) NOT NULL DEFAULT 'customer'
        CONSTRAINT chk_users_role CHECK (role IN ('customer', 'admin')),
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uq_users_email UNIQUE (email)
);

CREATE INDEX IF NOT EXISTS idx_users_role_created
    ON users (role, created_at DESC);

-- Optimised site images are stored in PostgreSQL so the Render-hosted API is
-- the durable media source for both catalogue records and the studio archive.
CREATE TABLE IF NOT EXISTS media_assets (
    path VARCHAR(500) PRIMARY KEY,
    mime_type VARCHAR(100) NOT NULL
        CONSTRAINT chk_media_assets_image_type CHECK (mime_type LIKE 'image/%'),
    content BYTEA NOT NULL,
    sha256 CHAR(64) NOT NULL,
    size_bytes BIGINT NOT NULL
        CONSTRAINT chk_media_assets_size CHECK (size_bytes > 0),
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX IF NOT EXISTS idx_media_assets_sha256
    ON media_assets (sha256);

CREATE TABLE IF NOT EXISTS artworks (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    slug VARCHAR(160) NOT NULL,
    title VARCHAR(180) NOT NULL,
    description TEXT,
    medium VARCHAR(180),
    category VARCHAR(30) NOT NULL DEFAULT 'painting'
        CONSTRAINT chk_artworks_category CHECK (
            category IN ('painting', 'drawing', 'mixed-media', 'photography', 'sculpture', 'other')
        ),
    year SMALLINT NOT NULL
        CONSTRAINT chk_artworks_year CHECK (year BETWEEN 1000 AND 9999),
    dimensions VARCHAR(180),
    price NUMERIC(12, 2)
        CONSTRAINT chk_artworks_price CHECK (price IS NULL OR price >= 0),
    status VARCHAR(20) NOT NULL DEFAULT 'available'
        CONSTRAINT chk_artworks_status CHECK (status IN ('available', 'sold', 'private')),
    image_url VARCHAR(500) NOT NULL,
    featured BOOLEAN NOT NULL DEFAULT FALSE,
    display_order INTEGER NOT NULL DEFAULT 0
        CONSTRAINT chk_artworks_display_order CHECK (display_order >= 0),
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uq_artworks_slug UNIQUE (slug)
);

CREATE INDEX IF NOT EXISTS idx_artworks_catalogue
    ON artworks (status, category, featured DESC, display_order);

CREATE TABLE IF NOT EXISTS products (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    slug VARCHAR(160) NOT NULL,
    name VARCHAR(180) NOT NULL,
    description TEXT,
    price NUMERIC(12, 2) NOT NULL
        CONSTRAINT chk_products_price CHECK (price >= 0),
    stock INTEGER NOT NULL DEFAULT 0
        CONSTRAINT chk_products_stock CHECK (stock >= 0),
    image_url VARCHAR(500) NOT NULL,
    category VARCHAR(30) NOT NULL DEFAULT 'Studio edition'
        CONSTRAINT chk_products_category CHECK (
            category IN ('Apparel', 'Accessories', 'Prints', 'Homeware', 'Studio edition', 'Other')
        ),
    colors JSONB NOT NULL DEFAULT '[]'::JSONB
        CONSTRAINT chk_products_colors_array CHECK (jsonb_typeof(colors) = 'array'),
    sizes JSONB NOT NULL DEFAULT '[]'::JSONB
        CONSTRAINT chk_products_sizes_array CHECK (jsonb_typeof(sizes) = 'array'),
    featured BOOLEAN NOT NULL DEFAULT FALSE,
    display_order INTEGER NOT NULL DEFAULT 0
        CONSTRAINT chk_products_display_order CHECK (display_order >= 0),
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uq_products_slug UNIQUE (slug)
);

CREATE INDEX IF NOT EXISTS idx_products_catalogue
    ON products (category, featured DESC, display_order);
CREATE INDEX IF NOT EXISTS idx_products_stock ON products (stock);

CREATE TABLE IF NOT EXISTS blog_posts (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    slug VARCHAR(160) NOT NULL,
    title VARCHAR(220) NOT NULL,
    excerpt VARCHAR(600),
    content TEXT NOT NULL,
    category VARCHAR(100),
    image_url VARCHAR(500),
    read_time_minutes SMALLINT NOT NULL DEFAULT 3
        CONSTRAINT chk_blog_read_time CHECK (read_time_minutes > 0),
    status VARCHAR(20) NOT NULL DEFAULT 'draft'
        CONSTRAINT chk_blog_status CHECK (status IN ('draft', 'published')),
    author_id BIGINT NOT NULL,
    published_at TIMESTAMPTZ,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uq_blog_posts_slug UNIQUE (slug),
    CONSTRAINT fk_blog_posts_author
        FOREIGN KEY (author_id) REFERENCES users(id)
        ON UPDATE CASCADE ON DELETE RESTRICT
);

CREATE INDEX IF NOT EXISTS idx_blog_posts_public
    ON blog_posts (status, published_at DESC);

CREATE TABLE IF NOT EXISTS inquiries (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT,
    name VARCHAR(120) NOT NULL,
    email VARCHAR(254) NOT NULL,
    subject VARCHAR(220) NOT NULL,
    message TEXT NOT NULL,
    status VARCHAR(20) NOT NULL DEFAULT 'new'
        CONSTRAINT chk_inquiries_status CHECK (status IN ('new', 'read', 'replied', 'closed')),
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_inquiries_user
        FOREIGN KEY (user_id) REFERENCES users(id)
        ON UPDATE CASCADE ON DELETE SET NULL
);

CREATE INDEX IF NOT EXISTS idx_inquiries_status_created
    ON inquiries (status, created_at DESC);
CREATE INDEX IF NOT EXISTS idx_inquiries_user ON inquiries (user_id);

CREATE TABLE IF NOT EXISTS contacts (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(120) NOT NULL,
    email VARCHAR(254) NOT NULL,
    topic VARCHAR(20) NOT NULL
        CONSTRAINT chk_contacts_topic CHECK (topic IN ('purchase', 'commission', 'merch', 'press', 'other')),
    message TEXT NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX IF NOT EXISTS idx_contacts_created ON contacts (created_at DESC);

CREATE TABLE IF NOT EXISTS orders (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    reference VARCHAR(32) NOT NULL,
    user_id BIGINT NOT NULL,
    total_amount NUMERIC(12, 2) NOT NULL
        CONSTRAINT chk_orders_total CHECK (total_amount >= 0),
    shipping_address JSONB NOT NULL
        CONSTRAINT chk_orders_shipping_object CHECK (jsonb_typeof(shipping_address) = 'object'),
    status VARCHAR(20) NOT NULL DEFAULT 'pending'
        CONSTRAINT chk_orders_status CHECK (
            status IN ('pending', 'paid', 'processing', 'shipped', 'delivered', 'cancelled')
        ),
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uq_orders_reference UNIQUE (reference),
    CONSTRAINT fk_orders_user
        FOREIGN KEY (user_id) REFERENCES users(id)
        ON UPDATE CASCADE ON DELETE RESTRICT
);

CREATE INDEX IF NOT EXISTS idx_orders_user_created
    ON orders (user_id, created_at DESC);
CREATE INDEX IF NOT EXISTS idx_orders_status_created
    ON orders (status, created_at DESC);

CREATE TABLE IF NOT EXISTS order_items (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    order_id BIGINT NOT NULL,
    product_id BIGINT,
    artwork_id BIGINT,
    quantity SMALLINT NOT NULL
        CONSTRAINT chk_order_items_quantity CHECK (quantity > 0),
    price NUMERIC(12, 2) NOT NULL
        CONSTRAINT chk_order_items_price CHECK (price >= 0),
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT chk_order_item_source CHECK (
        (product_id IS NOT NULL AND artwork_id IS NULL)
        OR (product_id IS NULL AND artwork_id IS NOT NULL)
    ),
    CONSTRAINT fk_order_items_order
        FOREIGN KEY (order_id) REFERENCES orders(id)
        ON UPDATE CASCADE ON DELETE CASCADE,
    CONSTRAINT fk_order_items_product
        FOREIGN KEY (product_id) REFERENCES products(id)
        ON UPDATE CASCADE ON DELETE RESTRICT,
    CONSTRAINT fk_order_items_artwork
        FOREIGN KEY (artwork_id) REFERENCES artworks(id)
        ON UPDATE CASCADE ON DELETE RESTRICT
);

CREATE INDEX IF NOT EXISTS idx_order_items_order ON order_items (order_id);
CREATE INDEX IF NOT EXISTS idx_order_items_product ON order_items (product_id);
CREATE INDEX IF NOT EXISTS idx_order_items_artwork ON order_items (artwork_id);

CREATE OR REPLACE FUNCTION set_updated_at()
RETURNS TRIGGER AS $$
BEGIN
    NEW.updated_at = CURRENT_TIMESTAMP;
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

DROP TRIGGER IF EXISTS trg_users_updated_at ON users;
CREATE TRIGGER trg_users_updated_at
    BEFORE UPDATE ON users
    FOR EACH ROW EXECUTE FUNCTION set_updated_at();

DROP TRIGGER IF EXISTS trg_media_assets_updated_at ON media_assets;
CREATE TRIGGER trg_media_assets_updated_at
    BEFORE UPDATE ON media_assets
    FOR EACH ROW EXECUTE FUNCTION set_updated_at();

DROP TRIGGER IF EXISTS trg_artworks_updated_at ON artworks;
CREATE TRIGGER trg_artworks_updated_at
    BEFORE UPDATE ON artworks
    FOR EACH ROW EXECUTE FUNCTION set_updated_at();

DROP TRIGGER IF EXISTS trg_products_updated_at ON products;
CREATE TRIGGER trg_products_updated_at
    BEFORE UPDATE ON products
    FOR EACH ROW EXECUTE FUNCTION set_updated_at();

DROP TRIGGER IF EXISTS trg_blog_posts_updated_at ON blog_posts;
CREATE TRIGGER trg_blog_posts_updated_at
    BEFORE UPDATE ON blog_posts
    FOR EACH ROW EXECUTE FUNCTION set_updated_at();

DROP TRIGGER IF EXISTS trg_inquiries_updated_at ON inquiries;
CREATE TRIGGER trg_inquiries_updated_at
    BEFORE UPDATE ON inquiries
    FOR EACH ROW EXECUTE FUNCTION set_updated_at();

DROP TRIGGER IF EXISTS trg_orders_updated_at ON orders;
CREATE TRIGGER trg_orders_updated_at
    BEFORE UPDATE ON orders
    FOR EACH ROW EXECUTE FUNCTION set_updated_at();

-- Additive and repeatable: existing users, media and orders are preserved.
ALTER TABLE users ADD COLUMN IF NOT EXISTS email_verified_at TIMESTAMPTZ;
ALTER TABLE users ADD COLUMN IF NOT EXISTS session_version INTEGER NOT NULL DEFAULT 0;
CREATE TABLE IF NOT EXISTS auth_challenges (
 id UUID PRIMARY KEY,
 email VARCHAR(254) NOT NULL,
 purpose VARCHAR(20) NOT NULL CHECK (purpose IN ('register','login','reset','email')),
 code_hash CHAR(64) NOT NULL,
 payload JSONB NOT NULL DEFAULT '{}',
 attempts INTEGER NOT NULL DEFAULT 0,
 expires_at TIMESTAMPTZ NOT NULL,
 created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);
CREATE INDEX IF NOT EXISTS idx_auth_challenges_expiry ON auth_challenges(expires_at);
CREATE TABLE IF NOT EXISTS auth_delivery_limits (
 email_key CHAR(64) PRIMARY KEY,
 window_start TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
 last_sent_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
 sends INTEGER NOT NULL DEFAULT 0
);
CREATE TABLE IF NOT EXISTS wishlists (
 user_id BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
 slug VARCHAR(160) NOT NULL,
 created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
 PRIMARY KEY (user_id, slug)
);
